// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	ID          int    `json:"id"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	PhoneNumber int    `json:"phoneNumber"`
	Email       string `json:"email"`
}
